version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "prettier"

exclude_patterns = [
  "src/Mireya.Database.Postgres/**",
  "src/Mireya.Database.Sqlite/**",
]